#!/usr/bin/env node
const assert=require('assert');
const domainCore=require('../../ready-assignment-domain-v2.js');
const learning=require('../../ready-learning-master-v01.js');
class MemoryStorage{constructor(){this.m=new Map()}getItem(k){return this.m.has(k)?this.m.get(k):null}setItem(k,v){this.m.set(k,String(v))}}
const domain=domainCore.createDomain(new MemoryStorage());
const books=domainCore.TALENT_BOOKS.map((subject,i)=>({subject,source_range:`p.${i*4+1}~${i*4+4}`,teacher_instruction:subject==='수학'?'분수 개념과 적용':'',artifact_refs:[`cover_${subject}`],answer_reference_ids:[`answer_${subject}`]}));
const pkg=domain.upsertTalentPackage({actor:'PARENT',source_date:'2026-09-15',deadline_boundary:'2026-09-22',books});
assert.strictEqual(pkg.fact_ids.length,6);
let state=domain.load();
for(const assignmentId of pkg.fact_ids)domain.confirmFact(assignmentId,{actor:'PARENT'});
state=domain.load();
const all=[];
for(const assignmentId of pkg.fact_ids)all.push(learning.interpretInto(state,assignmentId));
domain.save(state);
assert.strictEqual(all.length,6);
assert(all.every(x=>x.analysis.primary_split_basis==='LEARNING_UNIT'));
assert(all.every(x=>x.analysis.minutes_role==='OBSERVATION_ONLY'));
assert(all.every(x=>x.learning_units.length===1));
const math=all.flatMap(x=>x.learning_units).find(x=>x.subject==='수학');
assert(math.activity_types.includes('CONCEPT'));
assert(math.cognitive_load_profile.includes('ERROR_CORRECTION'));
assert.strictEqual(math.concept_skill_target,'분수 개념과 적용');
assert(!('estimated_minutes' in math));
assert(!('page_count' in math));
const workbook=domain.upsertWorkbookRef({name:'English Workbook A',subject:'영어',provenance:{kind:'PARENT_CAPTURE'}});
const pending=domain.upsertEnglishAssignment({assignment_id:'eng_1',actor:'CHILD',workbook_ref_id:workbook.workbook_ref_id,source_date:'2026-09-16',source_range:'p.32~41',weekday_prints:{MON:'print A',WED:'print B'},components:{vocabulary:'unit 3',listening:'track 4'},next_academy:''});
assert.throws(()=>learning.interpretFact(pending),/FACT_CONFIRMED/);
domain.confirmFact('eng_1',{actor:'PARENT'});
state=domain.load();
assert.throws(()=>learning.interpretFact(state.assignmentFacts.eng_1),/NEXT_ACADEMY_UNVERIFIED/);
const eng2=domain.upsertEnglishAssignment({assignment_id:'eng_2',actor:'PARENT',workbook_ref_id:workbook.workbook_ref_id,source_date:'2026-09-16',source_range:'p.32~41',weekday_prints:{MON:'print A',WED:'print B'},components:{vocabulary:'unit 3',listening:'track 4',recording:'sentence 2',writing:'paragraph 1'},next_academy:'2026-09-23'});
domain.confirmFact(eng2.assignment_id,{actor:'PARENT'});
state=domain.load();
const interpreted=learning.interpretInto(state,eng2.assignment_id);
assert.strictEqual(interpreted.learning_units.length,7);
assert.strictEqual(interpreted.learning_units.filter(x=>x.divisible_boundary==='PRINT_UNIT').length,2);
assert(interpreted.learning_units.every(x=>x.assignment_id==='eng_2'));
const conflictId='eng_conflict';
domain.upsertEnglishAssignment({assignment_id:conflictId,actor:'PARENT',workbook_ref_id:workbook.workbook_ref_id,source_date:'2026-09-16',source_range:'p.1~5',next_academy:'2026-09-23'});
domain.upsertEnglishAssignment({assignment_id:conflictId,actor:'CHILD',workbook_ref_id:workbook.workbook_ref_id,source_date:'2026-09-16',source_range:'p.1~8',next_academy:'2026-09-23'});
state=domain.load();
assert.strictEqual(state.assignmentFacts[conflictId].confirmation_state,'CONFIRMATION_REQUIRED');
assert.throws(()=>domain.confirmFact(conflictId,{actor:'PARENT'}),/conflict resolution required/);
console.log(JSON.stringify({pass:true,talent_books:6,english_units:7,physical_page_not_learning_unit:true,minutes_not_primary:true,conflict_blocks_interpretation:true}));
