const VERSION={app:'0.9.0',master:'REV_06',schema:3,cache:'ready-set-v090'};
const $=(s,r=document)=>r.querySelector(s);const $$=(s,r=document)=>[...r.querySelectorAll(s)];
const categories={재능:['국어','한자','피자','수학','연산','기타'],학교:['독서','글쓰기','숙제','준비물','기타'],영어:['라이팅','문장 녹음','단어 외우기','기타']};
const initial={schemaVersion:3,profile:{name:'',photo:'',style:'editorial'},guide:{name:'루미'},selected:[],tasks:[],targetMin:25,sound:'집중 피아노',records:[],activeSession:null,recordingMeta:null};
let state=load();let mediaRecorder=null,mediaStream=null,chunks=[],recordStartedAt=0,recordTicker=null,currentAudio=null;
function load(){try{const x=JSON.parse(localStorage.getItem('readyset_state')||'null');if(!x)return structuredClone(initial);return migrate(x)}catch{return structuredClone(initial)}}
function migrate(x){if(!x.schemaVersion)x.schemaVersion=1;if(x.schemaVersion<3){x.profile=x.profile||{name:'',photo:'',style:'editorial'};x.guide=x.guide||{name:'루미'};x.records=x.records||[];x.selected=x.selected||[];x.tasks=x.tasks||[];x.targetMin=x.targetMin||25;x.sound=x.sound||'집중 피아노';x.schemaVersion=3}return {...structuredClone(initial),...x,profile:{...initial.profile,...x.profile},guide:{...initial.guide,...x.guide}}}
function save(){localStorage.setItem('readyset_state',JSON.stringify(state))}
function toast(msg){const t=$('#toast');t.textContent=msg;t.hidden=false;clearTimeout(t._tm);t._tm=setTimeout(()=>t.hidden=true,2200)}
function nav(name){$$('.view').forEach(v=>v.classList.toggle('active',v.dataset.view===name));window.scrollTo(0,0);if(name==='home')renderHome();if(name==='mission')renderMission();if(name==='focus')renderFocus();if(name==='history')renderHistory();if(name==='calendar')renderCalendar();if(name==='profile')renderProfile();if(name==='settings')renderSettings();if(name==='result')renderResult()}
$$('[data-nav]').forEach(b=>b.addEventListener('click',()=>nav(b.dataset.nav)));
function initials(){return (state.profile.name||'RS').trim().slice(0,2).toUpperCase()}
function applyAvatar(el){if(!el)return;if(state.profile.photo){el.textContent='';el.style.backgroundImage=`url(${state.profile.photo})`;el.style.backgroundSize='cover';el.style.backgroundPosition='center';el.style.filter=styleFilter(state.profile.style)}else{el.textContent=initials();el.style.backgroundImage='none';el.style.filter='none'}}
function styleFilter(s){return {editorial:'saturate(.95) contrast(1.03)',storybook:'saturate(.72) sepia(.14) brightness(1.06)',graphic:'saturate(1.2) contrast(1.12)',natural:'saturate(.86) contrast(.96) brightness(1.04)'}[s]||'none'}
function renderHome(){applyAvatar($('#homeAvatar'));$('#heroTime').textContent=fmt(state.targetMin*60000);renderChips($('#homeChips'))}
function renderChips(root){root.innerHTML='';state.selected.forEach(x=>{const s=document.createElement('span');s.textContent=x;root.appendChild(s)})}
let sheetCategory='';function openCategory(cat){sheetCategory=cat;$('#sheetTitle').textContent=`${cat} · 세부 과제 선택`;const root=$('#sheetOptions');root.innerHTML='';categories[cat].forEach(item=>{const key=`${cat} · ${item}`;const b=document.createElement('button');b.textContent=item;b.classList.toggle('on',state.selected.includes(key));b.onclick=()=>{state.selected.includes(key)?state.selected=state.selected.filter(v=>v!==key):state.selected.push(key);b.classList.toggle('on');save();renderMission();renderHome()};root.appendChild(b)});$('#categorySheet').hidden=false}
$$('[data-category]').forEach(b=>b.addEventListener('click',()=>openCategory(b.dataset.category)));$$('[data-close-sheet]').forEach(b=>b.addEventListener('click',()=>$('#categorySheet').hidden=true));
function renderMission(){renderChips($('#missionChips'));const tl=$('#taskList');tl.innerHTML='';state.tasks.forEach((t,i)=>{const row=document.createElement('div');row.className='taskRow';row.innerHTML=`<span>${escapeHtml(t)}</span><button aria-label="삭제">×</button>`;row.querySelector('button').onclick=()=>{state.tasks.splice(i,1);save();renderMission()};tl.appendChild(row)});$$('[data-minutes]').forEach(b=>b.classList.toggle('on',String(state.targetMin)===b.dataset.minutes));$('#customMinutes').value=state.targetMin;$('#soundName').textContent=state.sound;const labels=[...state.selected,...state.tasks];$('#missionPreviewText').textContent=`${labels.length?labels.join(' · '):'과제를 선택해 주세요'} · ${state.targetMin}분`}
$('#addTaskBtn').onclick=()=>{const v=$('#taskInput').value.trim();if(!v)return;state.tasks.push(v);$('#taskInput').value='';save();renderMission()};
$$('[data-minutes]').forEach(b=>b.onclick=()=>{if(b.dataset.minutes==='custom'){ $('#customTimeWrap').hidden=false;return }$('#customTimeWrap').hidden=true;state.targetMin=+b.dataset.minutes;save();renderMission()});
$('#customMinutes').onchange=e=>{state.targetMin=Math.max(1,Math.min(180,+e.target.value||25));save();renderMission()};
function openSound(){const sh=$('#soundSheet');sh.hidden=false;$$('[data-sheet-sound]').forEach(b=>b.classList.toggle('on',b.dataset.sheetSound===state.sound))}$('#soundBtn').onclick=openSound;$('#focusSoundBtn').onclick=openSound;$('#changeBgm').onclick=openSound;$$('[data-close-sound]').forEach(b=>b.onclick=()=>$('#soundSheet').hidden=true);$$('[data-sheet-sound]').forEach(b=>b.onclick=()=>{state.sound=b.dataset.sheetSound;save();$('#soundName').textContent=state.sound;renderFocus();renderSettings()});
$('#startBtn').onclick=()=>{if(!state.selected.length&&!state.tasks.length){toast('먼저 오늘의 과제를 선택해 주세요.');return}const now=Date.now();state.activeSession={id:`s_${now}`,startAt:now,targetMs:state.targetMin*60000,pausedAt:null,issueMs:0,completed:false,selected:[...state.selected],tasks:[...state.tasks],sound:state.sound,recordingDone:false};save();nav('focus')};
function sessionTimes(){const s=state.activeSession;if(!s)return{focus:0,issue:0,remaining:state.targetMin*60000};const now=s.completed?s.endAt:Date.now();const currentPause=s.pausedAt?now-s.pausedAt:0;const issue=(s.issueMs||0)+currentPause;const elapsed=Math.max(0,now-s.startAt);const focus=Math.max(0,elapsed-issue);return{focus,issue,remaining:s.targetMs-focus}}
function fmt(ms){ms=Math.max(0,Math.floor(ms/1000));const m=Math.floor(ms/60),s=ms%60;return `${String(m).padStart(2,'0')}:${String(s).padStart(2,'0')}`}
function fmtSigned(ms){return `${ms<0?'-':'+'}${fmt(Math.abs(ms))}`}
function renderFocus(){const s=state.activeSession;if(!s){nav('mission');return}const labels=[...s.selected,...s.tasks];$('#focusMission').textContent=labels.join(' · ')||'오늘의 작전';$('#recBtn').hidden=!s.selected.includes('영어 · 문장 녹음');$('#targetTime').textContent=fmt(s.targetMs);$('#startClock').textContent=new Date(s.startAt).toLocaleTimeString('ko-KR',{hour:'2-digit',minute:'2-digit',hour12:false});$('#bgmStatus').textContent=s.pausedAt?'잠깐 멈춤':`${s.sound} · ${s.sound==='OFF'?'꺼짐':'재생 중'}`;tickFocus()}
function tickFocus(){const s=state.activeSession;if(!s)return;const t=sessionTimes();$('#remainingTime').textContent=t.remaining>=0?fmt(t.remaining):`+${fmt(-t.remaining)}`;$('#focusElapsed').textContent=fmt(t.focus);$('#issueElapsed').textContent=fmt(t.issue);$('#pauseBtn').textContent=s.pausedAt?'다시, 작전 속으로':'잠깐 멈춤';const d=new Date();$('#secondHand').style.transform=`rotate(${d.getSeconds()*6}deg)`;$('#minuteHand').style.transform=`rotate(${d.getMinutes()*6+d.getSeconds()*.1}deg)`;$('#hourHand').style.transform=`rotate(${((d.getHours()%12)*30)+d.getMinutes()*.5}deg)`;if(!s.completed&&$('#focusView').classList.contains('active'))requestAnimationFrame(tickFocus)}
$('#pauseBtn').onclick=()=>{const s=state.activeSession;if(!s)return;if(s.pausedAt){s.issueMs+=(Date.now()-s.pausedAt);s.pausedAt=null}else{s.pausedAt=Date.now()}save();renderFocus()};
$('#completeBtn').onclick=()=>completeSession();
function completeSession(){const s=state.activeSession;if(!s)return;if(s.pausedAt){s.issueMs+=Date.now()-s.pausedAt;s.pausedAt=null}s.endAt=Date.now();s.completed=true;const t=sessionTimes();const rec={...s,focusMs:t.focus,issueMs:t.issue,deltaMs:t.focus-s.targetMs};state.records.unshift(rec);state.records=state.records.slice(0,200);state.activeSession=null;save();state.lastResult=rec;nav('result')}
$('#recBtn').onclick=()=>$('#recIntro').hidden=false;$('#cancelRecordBtn').onclick=()=>$('#recIntro').hidden=true;$('#goRecordBtn').onclick=()=>{$('#recIntro').hidden=true;nav('recording');renderRecordingContext()};$('#recordBackBtn').onclick=()=>nav('focus');
function renderRecordingContext(){const t=sessionTimes();$('#recordTimerContext').textContent=t.remaining>=0?fmt(t.remaining):`+${fmt(-t.remaining)}`;applyAvatar($('#recordAvatar'));$('#guideDialogue').textContent=`${state.guide.name}, 오늘은 네 목소리를 같이 들어볼게. 천천히, 자신 있게 읽어봐.`}
$('#recordAction').onclick=async()=>{if(mediaRecorder&&mediaRecorder.state==='recording'){mediaRecorder.stop();return}await startRecording()};
async function startRecording(){if(!navigator.mediaDevices?.getUserMedia){toast('이 브라우저는 마이크 녹음을 지원하지 않습니다.');return}try{mediaStream=await navigator.mediaDevices.getUserMedia({audio:{echoCancellation:true,noiseSuppression:true,autoGainControl:true}});const candidates=['audio/mp4;codecs=mp4a.40.2','audio/mp4','audio/webm;codecs=opus','audio/webm'];const mime=candidates.find(m=>window.MediaRecorder&&MediaRecorder.isTypeSupported?.(m))||'';mediaRecorder=new MediaRecorder(mediaStream,mime?{mimeType:mime}:undefined);chunks=[];mediaRecorder.ondataavailable=e=>{if(e.data.size)chunks.push(e.data)};mediaRecorder.onstop=finishRecording;mediaRecorder.start(250);recordStartedAt=Date.now();$('#recordAction').classList.add('recording');$('#recordAction span').textContent='녹음 끝내기';$('#recordState').textContent='RECORDING';$('#waveform').classList.add('active');recordTicker=setInterval(()=>{$('#recordClock').textContent=fmt(Date.now()-recordStartedAt);renderRecordingContext()},250)}catch(e){toast(e.name==='NotAllowedError'?'마이크 권한이 필요합니다.':'녹음을 시작할 수 없습니다.') }}
function finishRecording(){clearInterval(recordTicker);mediaStream?.getTracks().forEach(t=>t.stop());$('#recordAction').classList.remove('recording');$('#recordAction span').textContent='녹음 시작';$('#recordState').textContent='REVIEW';$('#waveform').classList.remove('active');const type=mediaRecorder.mimeType||chunks[0]?.type||'audio/webm';currentAudio=new Blob(chunks,{type});$('#audioPreview').src=URL.createObjectURL(currentAudio);$('#reviewPanel').hidden=false;$('#guideDialogue').textContent='잠깐만. 같이 들어줄 친구 좀 잡아올게!';const isM4A=/audio\/(mp4|m4a)/.test(type);$('#formatNote').textContent=isM4A?'이 브라우저에서는 M4A/MP4 계열 오디오로 저장할 수 있습니다.':'이 브라우저의 원본 녹음 포맷은 WebM입니다. .m4a로 이름만 바꾸지 않으며, M4A 제출이 필요하면 변환 계층이 필요합니다.';state.recordingMeta={mime:type,durationMs:Date.now()-recordStartedAt};save()}
$('#rerecordBtn').onclick=()=>{$('#reviewPanel').hidden=true;currentAudio=null;$('#recordClock').textContent='00:00';$('#recordState').textContent='READY'};
$('#saveRecordingBtn').onclick=async()=>{if(!currentAudio)return;const type=currentAudio.type||'audio/webm';const ext=/audio\/(mp4|m4a)/.test(type)?'m4a':'webm';const d=new Date(),date=`${d.getFullYear()} ${String(d.getMonth()+1).padStart(2,'0')} ${String(d.getDate()).padStart(2,'0')}`;const base=(state.profile.name||'Judy').replace(/[\\/:*?"<>|]/g,'_');const filename=`${base}'s grammar recording ${date}.${ext}`;await storeAudio(currentAudio,filename,type);if(state.activeSession)state.activeSession.recordingDone=true;save();toast(`저장 완료 · ${filename}`);setTimeout(()=>nav('focus'),650)};
function storeAudio(blob,name,type){return new Promise((resolve,reject)=>{const req=indexedDB.open('readyset_audio',1);req.onupgradeneeded=()=>req.result.createObjectStore('audio',{keyPath:'id'});req.onerror=()=>reject(req.error);req.onsuccess=()=>{const tx=req.result.transaction('audio','readwrite');tx.objectStore('audio').put({id:`a_${Date.now()}`,name,type,blob,createdAt:Date.now()});tx.oncomplete=resolve;tx.onerror=()=>reject(tx.error)}})}
function resultSource(){return state.lastResult||state.records[0]||null}
function renderResult(){const r=resultSource();if(!r)return;applyAvatar($('#resultAvatar'));const delta=r.deltaMs;let headline,line,label='차이';if(delta<=-120000){headline='엣헴~! 오늘 좀 했습니다.';line='잠깐… 시계보다 먼저 왔는데?';label='TIME SAVE'}else if(Math.abs(delta)<=60000){headline='오? 계산대로인데?';line='시계랑 거의 동시에 들어왔어요.'}else if(delta>0){headline='무사 귀환!';line='헤헤… 조금 늦었습니다. 그래도 작전 완료!'}else{headline='작전 완료!';line='오늘도 끝까지 잘 돌아왔어요.'}$('#resultHeadline').textContent=headline;$('#resultLine').textContent=line;$('#resultTasks').textContent=[...r.selected,...r.tasks].join(' · ');$('#resultTarget').textContent=fmt(r.targetMs);$('#resultFocus').textContent=fmt(r.focusMs);$('#deltaLabel').textContent=label;$('#resultDelta').textContent=fmt(Math.abs(delta))}
function renderHistory(){const root=$('#historyList');root.innerHTML='';if(!state.records.length){root.innerHTML='<div class="historyItem"><b>아직 기록이 없어요.</b><p>첫 타임어택을 완료하면 여기에 쌓입니다.</p></div>';return}state.records.forEach(r=>{const x=document.createElement('article');x.className='historyItem';x.innerHTML=`<header><b>${new Date(r.endAt).toLocaleDateString('ko-KR')}</b><small>${fmt(r.focusMs)} / ${fmt(r.targetMs)}</small></header><p>${escapeHtml([...r.selected,...r.tasks].join(' · '))}</p>`;root.appendChild(x)})}
function renderCalendar(){const root=$('#calendarList');root.innerHTML='';state.records.slice(0,31).forEach(r=>{const x=document.createElement('article');x.className='historyItem';x.innerHTML=`<header><b>${new Date(r.endAt).toLocaleDateString('ko-KR')}</b><small>작전 완료</small></header><p>${escapeHtml([...r.selected,...r.tasks].join(' · '))}</p>`;root.appendChild(x)});if(!root.children.length)root.innerHTML='<div class="historyItem"><b>이번 달 작전 기록이 없어요.</b></div>'}
function renderProfile(){const img=$('#profileImage'),ph=$('#profilePlaceholder');$('#profileName').value=state.profile.name;if(state.profile.photo){img.src=state.profile.photo;img.hidden=false;ph.hidden=true;img.style.filter=styleFilter(state.profile.style)}else{img.hidden=true;ph.hidden=false;ph.textContent=initials()}$$('[data-style]').forEach(b=>b.classList.toggle('on',b.dataset.style===state.profile.style));document.documentElement.style.setProperty('--avatar-bg',state.profile.photo?`url(${state.profile.photo})`:'linear-gradient(145deg,#ffe7d6,#eaa789)')}
function photoLoad(file){if(!file)return;const r=new FileReader();r.onload=()=>{state.profile.photo=r.result;save();renderProfile()};r.readAsDataURL(file)}$('#cameraInput').onchange=e=>photoLoad(e.target.files[0]);$('#galleryInput').onchange=e=>photoLoad(e.target.files[0]);$$('[data-style]').forEach(b=>b.onclick=()=>{state.profile.style=b.dataset.style;save();renderProfile()});$('#saveProfileBtn').onclick=()=>{state.profile.name=$('#profileName').value.trim();save();toast('프로필을 저장했어요.');renderHome()};
function renderSettings(){$('#guideNameInput').value=state.guide.name;$('#guideNameLabel').textContent=state.guide.name;$$('[data-sound]').forEach(b=>b.classList.toggle('on',b.dataset.sound===state.sound))}$('#guideNameInput').onchange=e=>{state.guide.name=e.target.value.trim()||'루미';save();renderSettings()};$$('[data-sound]').forEach(b=>b.onclick=()=>{state.sound=b.dataset.sound;save();renderSettings()});
async function shareCard(kind='result'){const r=kind==='result'?resultSource():null;const c=document.createElement('canvas');c.width=1080;c.height=1350;const x=c.getContext('2d');x.fillStyle='#f6b197';x.fillRect(0,0,c.width,c.height);x.fillStyle='#fff8ef';roundRect(x,70,70,940,1210,54);x.fill();x.fillStyle='#2a231f';x.font='900 54px sans-serif';x.fillText('Ready & Set',120,160);x.font='900 76px sans-serif';x.fillText(kind==='result'?(r?.deltaMs<=-120000?'엣헴~! 오늘 좀 했습니다.':'오늘의 작전 완료!'):'작전 개시 전, 응원 요청!',120,270);x.fillStyle='#e88d6e';x.beginPath();x.arc(290,600,145,0,Math.PI*2);x.fill();x.fillStyle='#fff';x.font='900 74px sans-serif';x.textAlign='center';x.fillText(initials(),290,625);x.fillStyle='#456552';x.beginPath();x.arc(760,650,86,0,Math.PI*2);x.fill();x.fillStyle='#fff';x.font='900 54px sans-serif';x.fillText(state.guide.name.slice(0,1),760,668);x.textAlign='left';x.fillStyle='#2a231f';x.font='700 33px sans-serif';const text=kind==='result'?[...(r?.selected||[]),...(r?.tasks||[])].join(' · '):[...state.selected,...state.tasks].join(' · ');wrapText(x,text||'오늘의 작전',120,900,820,48);x.font='900 48px sans-serif';if(kind==='result'&&r){x.fillText(`목표 ${fmt(r.targetMs)}   집중 ${fmt(r.focusMs)}`,120,1085)}else{x.fillText(`목표 ${state.targetMin}:00`,120,1085)}x.font='700 30px sans-serif';x.fillStyle='#7c665c';x.fillText(kind==='result'?'오늘 우리에게 이런 일이 있었다.':'응원 한 스푼 부탁해요!',120,1160);const blob=await new Promise(res=>c.toBlob(res,'image/png'));const file=new File([blob],`Ready_Set_${kind}_${Date.now()}.png`,{type:'image/png'});try{if(navigator.canShare?.({files:[file]})){await navigator.share({files:[file],text:kind==='result'?'Ready & Set 작전 완료!':'Ready & Set 작전 시작!'});return}const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=file.name;a.click();URL.revokeObjectURL(url);toast('공유 카드를 이미지로 저장했어요.')}catch(e){if(e.name!=='AbortError')toast('공유를 완료하지 못했어요.') }}
function roundRect(ctx,x,y,w,h,r){ctx.beginPath();ctx.roundRect(x,y,w,h,r)}function wrapText(ctx,text,x,y,maxW,lineH){let line='';for(const ch of text){const t=line+ch;if(ctx.measureText(t).width>maxW){ctx.fillText(line,x,y);line=ch;y+=lineH}else line=t}if(line)ctx.fillText(line,x,y)}
$('#preShareBtn').onclick=()=>shareCard('pre');$('#missionShareBtn').onclick=()=>shareCard('pre');$('#shareResultBtn').onclick=()=>shareCard('result');
$('#exportDataBtn').onclick=()=>{const blob=new Blob([JSON.stringify(state,null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`Ready_Set_Data_${new Date().toISOString().slice(0,10)}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)};$('#resetDataBtn').onclick=()=>{if(confirm('모든 로컬 Ready & Set 기록을 초기화할까요?')){localStorage.removeItem('readyset_state');location.reload()}};
function escapeHtml(s){return String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
window.addEventListener('visibilitychange',()=>{if(!document.hidden&&state.activeSession)renderFocus()});window.addEventListener('load',()=>{renderHome();if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js').catch(()=>{})});
