const VERSION={app:'0.9.3',master:'REV_06',schema:5,cache:'ready-set-v093'};
/* Existing Ready & Set runtime retained. Share contract moved to compact Kakao renderer below. */
const $=(s,r=document)=>r.querySelector(s);const $$=(s,r=document)=>[...r.querySelectorAll(s)];
const initial={schemaVersion:5,profile:{name:'',photo:'',style:'editorial',shareAvatar:false},share:{theme:'drop'},selected:[],tasks:[],targetMin:25,records:[],activeSession:null,lastResult:null};
let state=(()=>{try{return {...structuredClone(initial),...JSON.parse(localStorage.getItem('readyset_state')||'{}')}}catch{return structuredClone(initial)}})();
function save(){localStorage.setItem('readyset_state',JSON.stringify(state))}
function fmt(ms){ms=Math.max(0,Math.floor(ms/1000));const m=Math.floor(ms/60),s=ms%60;return `${String(m).padStart(2,'0')}:${String(s).padStart(2,'0')}`}
function initials(){return(state.profile?.name||'RS').trim().slice(0,2).toUpperCase()}
function resultSource(){return state.lastResult||state.records?.[0]||null}
function roundRect(ctx,x,y,w,h,r){ctx.beginPath();ctx.roundRect?ctx.roundRect(x,y,w,h,r):ctx.rect(x,y,w,h)}
function loadImage(src){return new Promise((res,rej)=>{const i=new Image();i.onload=()=>res(i);i.onerror=rej;i.src=src})}
async function drawAvatar(ctx,cx,cy,r){if(state.profile?.shareAvatar&&state.profile?.photo){try{const img=await loadImage(state.profile.photo);ctx.save();ctx.beginPath();ctx.arc(cx,cy,r,0,Math.PI*2);ctx.clip();const sc=Math.max(r*2/img.width,r*2/img.height);ctx.drawImage(img,cx-img.width*sc/2,cy-img.height*sc/2,img.width*sc,img.height*sc);ctx.restore();return}catch{}}ctx.fillStyle='#f0a886';ctx.beginPath();ctx.arc(cx,cy,r,0,Math.PI*2);ctx.fill();ctx.fillStyle='#fff';ctx.font=`900 ${r*.7}px sans-serif`;ctx.textAlign='center';ctx.textBaseline='middle';ctx.fillText(initials(),cx,cy)}
function shareTheme(){return state.share?.theme==='sail'?'sail':'drop'}
function themeCopy(theme,kind){if(theme==='sail')return kind==='result'?{title:'멋진 항해였어요!',sub:'오늘의 섬 탐험 완료'}:{title:'오늘의 할 일을 찾아 항해해볼까?',sub:'바다를 따라 오늘의 섬으로'};return kind==='result'?{title:'오늘의 할 일이 도착했어요!',sub:'오늘의 섬 탐험 완료'}:{title:'오늘의 할 일을 발견하러 가볼까?',sub:'아래로 내려가 오늘의 섬으로'}}
function drawIslandScene(x,theme){const sky=x.createLinearGradient(0,0,0,430);sky.addColorStop(0,'#64c9ff');sky.addColorStop(1,'#dff7ff');x.fillStyle=sky;x.fillRect(0,0,900,430);x.fillStyle='#25aee8';x.fillRect(0,300,900,130);x.fillStyle='#55b96a';x.beginPath();x.ellipse(560,300,245,100,0,0,Math.PI*2);x.fill();x.fillStyle='#87735e';x.beginPath();x.moveTo(370,305);x.lineTo(750,305);x.lineTo(670,410);x.lineTo(430,410);x.closePath();x.fill();x.fillStyle='#fff';x.fillRect(545,220,28,105);x.fillStyle='#ff6a45';x.beginPath();x.moveTo(570,225);x.lineTo(630,245);x.lineTo(570,258);x.fill();if(theme==='sail'){x.fillStyle='#8a5b35';x.fillRect(145,320,210,18);x.fillStyle='#fff7dc';x.beginPath();x.moveTo(245,150);x.lineTo(245,318);x.lineTo(110,295);x.closePath();x.fill();x.strokeStyle='#7a5a3c';x.lineWidth=7;x.stroke()}else{x.fillStyle='rgba(255,255,255,.88)';for(let i=0;i<5;i++){x.beginPath();x.ellipse(100+i*165,75+(i%2)*45,105,38,0,0,Math.PI*2);x.fill()}}}
async function renderShareCard(kind='result'){
 const r=kind==='result'?resultSource():null,theme=shareTheme(),copy=themeCopy(theme,kind);const c=document.createElement('canvas');c.width=900;c.height=600;const x=c.getContext('2d');
 x.fillStyle='#fff';x.fillRect(0,0,900,600);drawIslandScene(x,theme);
 x.fillStyle='rgba(255,255,255,.92)';roundRect(x,28,24,238,54,27);x.fill();x.fillStyle='#102d55';x.font='900 27px sans-serif';x.textAlign='left';x.fillText('Ready & Set',55,60);
 x.fillStyle='#0a3265';x.font='900 46px sans-serif';x.fillText(copy.title,40,145);x.font='700 23px sans-serif';x.fillText(copy.sub,42,182);
 await drawAvatar(x,theme==='sail'?300:245,theme==='sail'?325:285,58);
 const tasks=kind==='result'?[...(r?.selected||[]),...(r?.tasks||[])]:[...(state.selected||[]),...(state.tasks||[])];const total=Math.max(1,tasks.length);const done=kind==='result'?total:0;const focus=kind==='result'&&r?fmt(r.focusMs||0):'00:00';const stars=kind==='result'?Math.max(1,Math.min(30,done*5)):0;
 x.fillStyle='#fff';roundRect(x,0,430,900,170,0);x.fill();x.strokeStyle='#e5edf5';x.lineWidth=2;x.beginPath();x.moveTo(0,430);x.lineTo(900,430);x.stroke();
 const stats=[[kind==='result'?`${done}/${total}`:`${total}개`,kind==='result'?'완료 미션':'오늘의 미션'],[focus,'집중 시간'],[`+${stars}`,'획득 별']];stats.forEach((v,i)=>{const cx=150+i*300;x.textAlign='center';x.fillStyle='#0d3569';x.font='900 35px sans-serif';x.fillText(v[0],cx,495);x.fillStyle='#718098';x.font='700 18px sans-serif';x.fillText(v[1],cx,528);if(i<2){x.strokeStyle='#e2e8ef';x.beginPath();x.moveTo(cx+150,458);x.lineTo(cx+150,540);x.stroke()}});
 x.textAlign='left';x.fillStyle='#223d62';x.font='700 18px sans-serif';x.fillText(tasks.slice(0,3).join(' · ')||'오늘의 탐험',35,574);return c;
}
async function shareCard(kind='result'){
 const c=await renderShareCard(kind);const blob=await new Promise(res=>c.toBlob(res,'image/png',.94));const file=new File([blob],`Ready_Set_${shareTheme()}_${kind}_${Date.now()}.png`,{type:'image/png'});const text=kind==='result'?'Ready & Set · 오늘의 섬 탐험 완료!':'Ready & Set · 오늘의 탐험을 시작해요!';
 try{if(navigator.canShare?.({files:[file]})){await navigator.share({files:[file],title:'Ready & Set',text});return}const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=file.name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}catch(e){if(e.name!=='AbortError')console.error(e)}
}
/* Kakao Link payload: use when Kakao JS SDK is configured. Image must be an HTTPS URL; generated canvas image therefore needs upload/storage before sendDefault. */
function buildKakaoFeed({imageUrl,webUrl,kind='result'}={}){const r=kind==='result'?resultSource():null,theme=shareTheme(),copy=themeCopy(theme,kind);return{objectType:'feed',content:{title:copy.title,description:kind==='result'?`${copy.sub} · 집중 ${fmt(r?.focusMs||0)}`:copy.sub,imageUrl,link:{mobileWebUrl:webUrl,webUrl}},buttons:[{title:kind==='result'?'탐험 기록 보기':'탐험 응원하기',link:{mobileWebUrl:webUrl,webUrl}}]}}
window.ReadySetShare={renderShareCard,shareCard,buildKakaoFeed,setTheme(theme){state.share={...(state.share||{}),theme:theme==='sail'?'sail':'drop'};save()}};
window.addEventListener('load',()=>{document.querySelector('#preShareBtn')?.addEventListener('click',()=>shareCard('pre'));document.querySelector('#missionShareBtn')?.addEventListener('click',()=>shareCard('pre'));document.querySelector('#shareResultBtn')?.addEventListener('click',()=>shareCard('result'))});