(() => {
  'use strict';
  const VERSION='2026.09.08-stage-g1-intake-semantics';
  const ROLE=new URLSearchParams(location.search).get('role')==='parent'?'PARENT':'CHILD';
  const model=()=>window.ReadyAssignmentModel;
  const today=()=>new Date().toLocaleDateString('sv-SE');
  const esc=v=>String(v??'').replace(/[&<>"']/g,ch=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[ch]));
  const toast=msg=>window.toast?window.toast(msg):alert(msg);

  function styles(){
    if(document.getElementById('readyStageFStyle'))return;
    const s=document.createElement('style');s.id='readyStageFStyle';s.textContent=`
      .rsf-hide{display:none!important}.rsf-role-home{display:inline-flex;align-items:center;padding:6px 10px;border-radius:999px;background:#1f1f1d;color:#fff;font-size:10px;font-weight:900;letter-spacing:.02em;margin-left:auto;margin-right:8px}.rsf-role-home.parent{background:#385ea8}.rsf-card{border:1px solid rgba(0,0,0,.10);border-radius:22px;background:#fffdf8;padding:14px;margin:0 0 12px;box-shadow:0 8px 24px rgba(52,39,10,.06)}.rsf-card h2{margin:0 0 5px;font-size:20px}.rsf-card h3{margin:14px 0 6px;font-size:15px}.rsf-card p{margin:0;color:#756c5e;font-size:12px;line-height:1.45}.rsf-badge{display:inline-flex;padding:5px 8px;border-radius:999px;background:#fff1aa;color:#665100;font-size:10px;font-weight:900;margin:0 6px 6px 0}.rsf-badge.warn{background:#ffe0d8;color:#8a2d16}.rsf-list{display:grid;gap:8px;margin-top:12px}.rsf-task{display:grid;grid-template-columns:auto 1fr;gap:10px;padding:12px;border:1px solid #e4dccf;border-radius:16px;background:#fff}.rsf-task input[type=checkbox]{width:21px;height:21px;margin-top:3px}.rsf-task b{display:block}.rsf-task small{display:block;margin-top:4px;color:#7a7164;line-height:1.4}.rsf-grid{display:grid;grid-template-columns:1fr 1fr;gap:7px;margin-top:8px}.rsf-grid.three{grid-template-columns:1fr 1fr 1fr}.rsf-grid input,.rsf-grid select,.rsf-grid textarea,.rsf-event input,.rsf-book-row input{width:100%;box-sizing:border-box;padding:9px;border:1px solid #d9d0c1;border-radius:10px;background:#fff;font:inherit}.rsf-event{display:flex;gap:7px;margin-top:10px}.rsf-event input{flex:1;min-width:0}.rsf-btn{border:0;border-radius:12px;padding:11px 13px;font-weight:900;background:#1f1f1d;color:#fff}.rsf-btn.alt{background:#ffe275;color:#30280f}.rsf-section{margin-top:14px;padding-top:12px;border-top:1px dashed #d9cfae}.rsf-book-grid{display:grid;gap:7px;margin-top:8px}.rsf-book-row{display:grid;grid-template-columns:.85fr 1.1fr 1.1fr 1fr;gap:7px;align-items:center;padding:8px;background:#fff8df;border-radius:12px}.rsf-book-row b{font-size:12px}.rsf-fact{padding:10px;border-radius:12px;background:#f7f4ec;margin-top:7px}.rsf-fact b{font-size:12px}.rsf-fact small{display:block;margin-top:3px;color:#6f685e}.rsf-sticky{position:sticky;bottom:0;padding-top:10px;background:linear-gradient(180deg,rgba(255,253,248,0),#fffdf8 35%)}
      html[data-ready-role='CHILD'] #todayPlannerCard,html[data-ready-role='PARENT'] #todayPlannerCard{display:none!important}html[data-ready-role='CHILD'] #missionView .progressSteps{display:none!important}html[data-ready-role='PARENT'] #missionView .progressSteps,html[data-ready-role='PARENT'] #missionView .glassCard,html[data-ready-role='PARENT'] #missionView .missionPreview,html[data-ready-role='PARENT'] #missionView .stackActions{display:none!important}
      @media(max-width:560px){.rsf-book-row{grid-template-columns:1fr 1fr}.rsf-grid.three{grid-template-columns:1fr}.rsf-grid{grid-template-columns:1fr}}
    `;document.head.appendChild(s);
  }
  function ensureRoleMarker(){
    const top=document.querySelector('#homeView .topbar');if(!top)return;
    let m=document.getElementById('rsfRoleMarker');if(!m){m=document.createElement('span');m.id='rsfRoleMarker';top.insertBefore(m,top.lastElementChild||null)}
    m.className=`rsf-role-home ${ROLE==='PARENT'?'parent':''}`;m.textContent=ROLE==='PARENT'?'부모 모드':'아이 모드';
  }
  function explorerTerms(){
    if(ROLE!=='CHILD')return;
    const map=new Map([['타임어택 작전 설정','오늘의 탐험 준비'],['오늘 목표 정하기','오늘 탐험 정하기'],['작전 기록실','탐험 기록'],['작전 일지','탐험 일지'],['오늘의 작전 미리보기','오늘의 탐험 미리보기'],['작전 공유하기','가족에게 응원 요청'],['타임어택 START','탐험 시작'],['오늘의 작전 보고서','오늘의 탐험 기록'],['오늘의 작전','오늘의 탐험'],['오늘 작전, 내가 옆에서 같이 봐줄게.','오늘 탐험, 내가 옆에서 같이 봐줄게.']]);
    document.querySelectorAll('body *').forEach(el=>{if(el.children.length)return;const t=(el.textContent||'').trim();if(map.has(t))el.textContent=map.get(t)});
    const share=document.getElementById('missionShareBtn');if(share)share.textContent='가족에게 응원 요청 (선택)';
  }
  function hideLegacyChildSetup(){
    if(ROLE!=='CHILD')return;
    document.querySelectorAll('#missionView .glassCard').forEach(card=>{const h=card.querySelector('h2')?.textContent||'';if(h.includes('과제 분류')||h.includes('오늘 할 과제를 입력'))card.classList.add('rsf-hide')});
  }
  function normalizeHomeEntrypoints(){
    const share=document.getElementById('preShareBtn');if(share)share.style.display='none';
    const buttons=[...document.querySelectorAll('#homeView .commandCard > button')];
    const candidates=buttons.filter(btn=>/오늘 숙제 배포|오늘 목표 정하기|오늘 탐험 정하기|숙제 입력 · 확인/.test(btn.querySelector('b')?.textContent||''));
    if(candidates.length){const primary=candidates[0],b=primary.querySelector('b'),s=primary.querySelector('small');if(ROLE==='PARENT'){if(b)b.textContent='숙제 입력 · 확인';if(s)s.textContent='숙제 원본 FACT 촬영·입력·확인'}else{if(b)b.textContent='오늘 탐험 정하기';if(s)s.textContent='Planner가 준비한 오늘 할 일에서 선택'}candidates.slice(1).forEach(x=>x.style.display='none');if(!primary.dataset.nav)primary.dataset.nav='mission'}
    document.querySelectorAll('#homeView [data-nav="mission"]').forEach((btn,i)=>{if(candidates.includes(btn)&&btn!==candidates[0])return;if(!candidates.length||btn===candidates[0])return;if(i>0)btn.style.display='none'});
    if(ROLE==='PARENT'){const history=[...buttons].find(btn=>(btn.querySelector('b')?.textContent||'').includes('기록실'));if(history){const b=history.querySelector('b'),s=history.querySelector('small');if(b)b.textContent='학습 기록';if(s)s.textContent='아이의 진행과 완료 기록 보기'}}
  }
  function syncPlannerSelection(){window.ReadyStageD?.renderPlanner?.();setTimeout(()=>document.querySelector('#todayPlannerCard [data-plan-action="apply"]')?.click(),0)}
  function factStateLabel(f){return f.confirmationState==='FACT_CONFIRMED'?'확인됨':f.confirmationState==='CONFIRMATION_REQUIRED'?'확인 필요':'입력 중'}
  function factSummaryHTML({child=false}={}){
    const facts=model()?.assignmentView?.()||[];
    if(!facts.length)return '<div class="rsf-fact"><b>등록된 전체 숙제 FACT가 아직 없어요.</b><small>숙제 원본이 들어오면 오늘 할 일과 분리해서 보여줘요.</small></div>';
    return facts.slice(-14).reverse().map(f=>{const name=f.sourceType==='TALENT_BOOK_ASSIGNMENT'?`재능 · ${f.talentSubject}`:f.sourceType==='ENGLISH_ACADEMY_PACKAGE'?`영어 · ${f.workbook||'문제집'}`:f.title||f.subject||'숙제';const detail=[f.range,f.deadlineBoundary?`다음/마감 ${f.deadlineBoundary}`:'',f.sourceType==='ENGLISH_ACADEMY_PACKAGE'&&Object.values(f.printUnits||{}).filter(Boolean).length?`프린트 ${Object.values(f.printUnits||{}).filter(Boolean).length}개`:'' ].filter(Boolean).join(' · ');const warn=f.confirmationState==='CONFIRMATION_REQUIRED'?' warn':'';return `<div class="rsf-fact"><span class="rsf-badge${warn}">${esc(factStateLabel(f))}</span><b>${esc(name)}</b><small>${esc(detail||'세부 FACT 확인 필요')}</small>${child?'<small>전체 숙제 FACT · 오늘 실행 단위와 별도</small>':''}</div>`}).join('');
  }
  function renderChild(){
    const main=document.querySelector('#missionView main');if(!main)return;document.getElementById('rsfParent')?.remove();let root=document.getElementById('rsfChild');if(!root){root=document.createElement('section');root.id='rsfChild';root.className='rsf-card';main.prepend(root)}
    const p=model()?.load?.(),day=p?.days?.[today()]||{tasks:[]},tasks=(day.tasks||[]).filter(t=>t.status!=='COMPLETED');
    root.innerHTML=`<span class="rsf-badge">아이 화면 · 오늘의 탐험</span><h2>오늘 뭐부터 할까?</h2><p>Planner가 날짜별로 준비한 할 일에서 지금 할 것을 골라요. 전체 숙제 원본과 오늘 실행 단위는 서로 달라요.</p><div class="rsf-list">${tasks.length?tasks.map(t=>`<label class="rsf-task"><input type="checkbox" data-rsf-select="${esc(t.id)}" ${t.selected?'checked':''}><span><b>${esc(t.title||t.subject||'할 일')}</b><small>${esc(t.volume||'분량/단위 확인 필요')}${t.allocationState?.includes('PROVISIONAL')?' · 일정 확인 후 조정 가능':''}</small>${t.origin==='CHILD_ADDED'?'<span class="rsf-badge">내가 추가 · 부모 확인 가능</span>':''}</span></label>`).join(''):'<div class="rsf-task"><span></span><span><b>오늘 배정된 할 일이 아직 없어요.</b><small>새 숙제가 생겼다면 아래에서 FACT를 추가할 수 있어요.</small></span></div>'}</div><div class="rsf-event"><input id="rsfEventInput" placeholder="학교에서 새 숙제가 생겼어요"><button id="rsfEventAdd" class="rsf-btn">추가</button></div><div class="rsf-section"><h3>전체 숙제 FACT</h3><p>숙제 전체 범위/마감과 오늘 할 일은 따로 봐요.</p>${factSummaryHTML({child:true})}</div><div class="rsf-section"><h3>영어 숙제 범위를 직접 들었다면</h3><p>아이 입력도 FACT예요. 기존 입력과 다르면 자동으로 ‘확인 필요’가 됩니다.</p><div class="rsf-event"><input id="rsfChildEnglishRange" placeholder="예: p.32~41"><button id="rsfChildEnglishSave" class="rsf-btn alt">범위 기록</button></div></div>`;
    root.querySelectorAll('[data-rsf-select]').forEach(ch=>ch.onchange=()=>{const q=model().load(),d=q.days[today()]||{tasks:[]},t=d.tasks.find(x=>x.id===ch.dataset.rsfSelect);if(t)t.selected=ch.checked;model().save(q);syncPlannerSelection()});
    root.querySelector('#rsfEventAdd').onclick=()=>{const input=root.querySelector('#rsfEventInput'),title=input.value.trim();if(!title)return;model().addSchoolEvent({actor:'CHILD',title});renderChild();toast('새 숙제 FACT를 기록했고 Planner가 오늘 계획을 다시 보게 했어요.')};
    root.querySelector('#rsfChildEnglishSave').onclick=()=>{const range=root.querySelector('#rsfChildEnglishRange').value.trim();if(!range)return;const result=model().upsertEnglishPackage({actor:'CHILD',range});renderChild();toast(result.conflict?'기존 영어 FACT와 달라서 확인 필요로 표시했어요.':'영어 숙제 범위를 FACT로 기록했어요.')};
  }
  function existingTalentRanges(){const view=model()?.assignmentView?.()||[];const map={};view.filter(f=>f.sourceType==='TALENT_BOOK_ASSIGNMENT').forEach(f=>map[f.talentSubject]=f.range||'');return map}
  function renderParent(){
    const main=document.querySelector('#missionView main');if(!main)return;document.getElementById('rsfChild')?.remove();const h=document.querySelector('#missionView .pageHeader h1');if(h)h.textContent='숙제 입력 · 확인';let root=document.getElementById('rsfParent');if(!root){root=document.createElement('section');root.id='rsfParent';root.className='rsf-card';main.prepend(root)}
    const p=model()?.load?.()||{},talentRanges=existingTalentRanges(),english=(model()?.assignmentView?.()||[]).find(f=>f.sourceType==='ENGLISH_ACADEMY_PACKAGE')||{},workbookName=english.workbook||p.workbookRefs?.english_workbook_primary?.name||'';
    root.innerHTML=`<span class="rsf-badge">부모 화면 · FACT 입력/확인</span><h2>숙제 원본만 입력해 주세요</h2><p>부모는 숙제 FACT를 촬영·입력·확인합니다. 난이도·예상시간·날짜별 배정은 부모 입력 항목이 아닙니다.</p><div class="rsf-section"><h3>재능 · 이번 주 6권</h3><p>6권은 한 주 패키지지만 권별 원본 FACT는 따로 저장합니다. 다음 화요일은 다음 주기 경계/마감이지 정상 배정 슬롯이 아닙니다.</p><div class="rsf-book-grid">${(model()?.TALENT_SUBJECTS||[]).map(s=>`<div class="rsf-book-row" data-rsf-talent="${esc(s)}"><b>${esc(s)}</b><input data-range placeholder="이번 주 범위" value="${esc(talentRanges[s]||'')}"><input data-instruction placeholder="지시사항/문제 메모"><input data-answer placeholder="답안·해설 참고 메모"></div>`).join('')}</div><button id="rsfTalentFactSave" class="rsf-btn alt" style="width:100%;margin-top:8px">재능 6권 FACT 저장 · 확인</button></div><div class="rsf-section"><h3>영어 · 문제집 기준 + 다음 학원 전 숙제</h3><p>문제집은 재사용 기준으로 두고, 학원 후 실제 범위와 요일별 프린트/녹음/쓰기 등을 새 FACT로 기록합니다.</p><div class="rsf-grid"><input id="rsfEnglishWorkbook" placeholder="문제집 이름/기준" value="${esc(workbookName)}"><input id="rsfEnglishRange" placeholder="이번 범위 예: p.32~41" value="${esc(english.range||'')}"></div><div class="rsf-grid"><input id="rsfEnglishNext" type="date" aria-label="다음 영어학원 날짜" value="${esc(english.deadlineBoundary||'')}"><input id="rsfEnglishInstruction" placeholder="선생님 지시사항"></div><div class="rsf-grid three"><input data-print="MON" placeholder="월 프린트"><input data-print="TUE" placeholder="화 프린트"><input data-print="WED" placeholder="수 프린트"><input data-print="THU" placeholder="목 프린트"><input data-print="FRI" placeholder="금 프린트"><input data-print="SAT" placeholder="토 프린트"></div><div class="rsf-grid"><input data-component="vocabulary" placeholder="단어"><input data-component="listening" placeholder="듣기"><input data-component="recording" placeholder="녹음"><input data-component="writing" placeholder="쓰기/라이팅"></div><button id="rsfEnglishFactSave" class="rsf-btn alt" style="width:100%;margin-top:8px">영어 숙제 FACT 저장 · 확인</button></div><div class="rsf-section"><h3>현재 숙제 FACT</h3>${factSummaryHTML()}</div>`;
    root.querySelector('#rsfTalentFactSave').onclick=()=>{const books=[...root.querySelectorAll('[data-rsf-talent]')].map(row=>({subject:row.dataset.rsfTalent,range:row.querySelector('[data-range]').value.trim(),teacherInstruction:row.querySelector('[data-instruction]').value.trim(),answerReferenceNote:row.querySelector('[data-answer]').value.trim()}));const result=model().upsertTalentPackage({actor:'PARENT',books});renderParent();toast(result.allocation?.ok?'재능 숙제 FACT를 저장했고 Planner가 날짜별 할 일을 다시 계산했어요.':'재능 숙제 FACT를 저장했어요. 범위가 확인된 권부터 Planner가 처리합니다.')};
    root.querySelector('#rsfEnglishFactSave').onclick=()=>{const prints=Object.fromEntries([...root.querySelectorAll('[data-print]')].map(el=>[el.dataset.print,el.value.trim()]));const components=Object.fromEntries([...root.querySelectorAll('[data-component]')].map(el=>[el.dataset.component,el.value.trim()]));const result=model().upsertEnglishPackage({actor:'PARENT',workbookName:root.querySelector('#rsfEnglishWorkbook').value.trim(),range:root.querySelector('#rsfEnglishRange').value.trim(),nextAcademy:root.querySelector('#rsfEnglishNext').value,prints,components,teacherInstruction:root.querySelector('#rsfEnglishInstruction').value.trim()});renderParent();toast(result.allocation?.ok?'영어 숙제 FACT를 저장했고 Planner가 다음 학원 전 실행 단위를 다시 계산했어요.':'영어 숙제 FACT를 저장했어요. 다음 학원 날짜가 확인되어야 날짜별 배정을 확정할 수 있어요.')};
  }
  function patch(){ensureRoleMarker();normalizeHomeEntrypoints();explorerTerms();hideLegacyChildSetup();if(!model())return;if(ROLE==='PARENT')renderParent();else renderChild()}
  function validate(){const marker=document.getElementById('rsfRoleMarker')?.textContent||'';const primary=[...document.querySelectorAll('#homeView .commandCard > button')].find(b=>b.style.display!=='none'&&/오늘 탐험 정하기|숙제 입력 · 확인/.test(b.querySelector('b')?.textContent||''));return{version:VERSION,role:ROLE,roleMarker:marker,homePrimary:primary?.querySelector('b')?.textContent||null,childSurface:!!document.getElementById('rsfChild'),parentSurface:!!document.getElementById('rsfParent'),assignmentFactModel:!!model(),parentDifficultyInput:!!document.querySelector('#rsfParent [data-field="difficulty"]'),parentMinuteInput:!!document.querySelector('#rsfParent [data-field="estimatedMin"],#rsfParent [data-min]')}}
  function boot(){document.documentElement.dataset.readyStageF=VERSION;document.documentElement.dataset.readyRole=ROLE;styles();patch();let scheduled=false;const mo=new MutationObserver(()=>{if(scheduled)return;scheduled=true;requestAnimationFrame(()=>{scheduled=false;ensureRoleMarker();normalizeHomeEntrypoints();explorerTerms();hideLegacyChildSetup()})});mo.observe(document.getElementById('homeView')||document.body,{childList:true,subtree:true});window.ReadyStageF=Object.freeze({version:VERSION,role:ROLE,render:patch,validate})}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else boot();
})();