'use strict';
const assert=require('node:assert/strict');
const fs=require('node:fs');
const vm=require('node:vm');
const crypto=require('node:crypto');
const manifest=JSON.parse(fs.readFileSync('assets/character-formation/asset-manifest.json','utf8'));
assert.equal(manifest.status,'HARD_LOCK');
for(const [id,path] of Object.entries(manifest.asset_files.crew)){
  const actual=crypto.createHash('sha256').update(fs.readFileSync(path)).digest('hex');
  assert.equal(actual,manifest.asset_sources.core6_runtime_derivatives.sha256[id],id+' canonical asset byte hash');
}
const root={};
for(const file of ['src/identity/character-formation-journey-runtime.js',
                   'src/identity/character-formation-scene-runtime.js',
                   'src/identity/expedition-companion-presentation-runtime.js'])
  vm.runInNewContext(fs.readFileSync(file,'utf8'),{globalThis:root,console});
const roster=root.CharacterFormationJourneyRuntime.CREW;
const els=new Map();
function element(key){
  if(!els.has(key)){
    const attrs=new Map();
    const node={hidden:false,textContent:'',dataset:{},classList:{remove(){}},
      style:{backgroundImage:'',removeProperty(name){if(name==='background-image')this.backgroundImage='';}},
      setAttribute(k,v){attrs.set(k,v)},removeAttribute(k){attrs.delete(k)},getAttribute(k){return attrs.get(k)||null}};
    els.set(key,node);
  }
  return els.get(key);
}
let state={expedition:{}};
let images=[];
const registry={
  snapshot:()=>({state:'READY'}),
  manifest:()=>manifest,
  path:(group,id)=>manifest.asset_files?.[group]?.[id]?'./'+manifest.asset_files[group][id]:null
};
const app=root.ReadyExpeditionCompanionPresentation.create({
  getState:()=>state,query:element,roster,assetRegistry:registry,
  preparation:root.CharacterFormationSceneRuntime.preparationLineFor,
  imageFactory:()=>{
    const img={onload:null,onerror:null,set src(path){images.push(path);if(path.includes('/missing'))this.onerror?.();else this.onload?.();}};
    return img;
  }
});
(async()=>{
  let out=await app.renderHome();
  assert.equal(out.reason,'PRIMARY_COMPANION_NOT_SELECTED');
  assert.equal(element('#homeGuideCard').hidden,true,'must NOT silently show Dubi or legacy Lumi');
  assert.equal(images.length,0);
  state.expedition.primaryCompanionId='bogus';
  out=await app.renderMission();
  assert.equal(out.reason,'PRIMARY_COMPANION_NOT_IN_LOCKED_ROSTER');
  assert.equal(images.length,0);
  state.expedition.primaryCompanionId='ink';
  state.expedition.primaryCompanionAlias='나만의 잉크';
  out=await app.renderHome();
  assert.equal(out.ok,true);
  assert.equal(out.character_id,'ink');
  assert.equal(element('#homeGuideName').textContent,'나만의 잉크');
  assert.equal(element('#homeGuideLine').textContent,roster.find(x=>x.id==='ink').line);
  assert.equal(element('#homeGuideLine').dataset.dialogueSource,'CHARACTER_FORMATION_JOURNEY_CREW_INTRO');
  assert.equal(element('#homeGuidePortrait').dataset.characterId,'ink');
  assert.equal(element('#homeGuidePortrait').dataset.assetSha256,manifest.asset_sources.core6_runtime_derivatives.sha256.ink);
  assert.equal(element('#homeGuideCard').hidden,false);
  assert.equal(images.at(-1),'./'+manifest.asset_files.crew.ink);
  out=await app.renderMission();
  assert.equal(out.ok,true);
  assert.equal(element('#missionCompanionName').textContent,'나만의 잉크');
  assert.equal(element('#missionCompanionLine').textContent,
    root.CharacterFormationSceneRuntime.preparationLineFor('ink'));
  assert.equal(element('#missionCompanionLine').dataset.dialogueSource,'CHARACTER_FORMATION_SCENE_PREPARATION');
  out=await app.renderResult();
  assert.equal(out.ok,true);
  assert.equal(element('#resultCompanionName').textContent,'나만의 잉크');
  assert.equal(element('#resultGuidePortrait').dataset.characterId,'ink');
  assert.equal(element('#resultCompanionSlot').hidden,false);
  // Actual result summary is generated by Result owner. The companion is not misattributed with a fabricated result quote.
  state.expedition.primaryCompanionId='zero';
  state.expedition.primaryCompanionAlias='나의 제로';
  out=await app.renderHome();
  assert.equal(out.character_id,'zero');
  assert.equal(element('#homeGuideName').textContent,'나의 제로');
  assert.equal(element('#homeGuideLine').textContent,roster.find(x=>x.id==='zero').line);
  assert.equal(element('#homeGuidePortrait').dataset.characterId,'zero');
  assert.notEqual(element('#homeGuidePortrait').dataset.characterId,'ink');
  const realIndex=fs.readFileSync('index.html','utf8');
  assert.match(realIndex,/expedition-companion-presentation-runtime\.js/);
  assert.match(realIndex,/id="missionCompanionCard" hidden/);
  assert.match(realIndex,/id="resultCompanionSlot" hidden/);
  assert.doesNotMatch(realIndex,/id="homeGuideName">루미/);
  const appSource=fs.readFileSync('app.js','utf8');
  const presentationSource=fs.readFileSync('src/identity/expedition-companion-presentation-runtime.js','utf8');
  assert.match(presentationSource,/expedition\?\.primaryCompanionId/);
  assert.match(appSource,/expeditionCompanionPresenter\?\.renderHome/);
  assert.match(appSource,/expeditionCompanionPresenter\?\.renderMission/);
  assert.match(appSource,/expeditionCompanionPresenter\?\.renderResult/);
  const sceneSource=fs.readFileSync('src/identity/character-formation-scene-runtime.js','utf8');
  assert.doesNotMatch(sceneSource,/\|\|'dubi'/,'unselected character must NOT become Dubi');
  assert.match(sceneSource,/preparationLineFor/);
  console.log('PASS: explicit chosen Core6 ID / real source asset / child alias / source-attributed dialogue across Home and Goal; Result identity only, no invented line; missing and invalid selection fail closed.');
})().catch(e=>{console.error(e);process.exitCode=1;});
